### ISSUE TITLE
Output reprints every action

### ISSUE THREAD

**Issue by iboyperson** [isacikgoz/tldr#12]
Expected Behavior (from README): 
![image](https://github.com/isacikgoz/tldr/raw/master/img/screenplay.gif)

Actual Behavior:
![image](https://user-images.githubusercontent.com/10000914/57115864-3fda1900-6d06-11e9-976c-4a9ec7c1785a.gif)

The output gets reprinted in full every time an action is made. In the README it does not appear to work this way but if I am mistaken please close this issue. Thanks!

**Comment by isacikgoz** [comment]
Hey @iboyperson , thanks for the feedback. I've never faced with this issue before, can you give a little more info on your environment?

**Comment by iboyperson** [comment]
Sure! Here is the information I can see being needed. If you need anything else please specify.

Distro: Arch Linux
Shell: Zsh 5.7.1
Go: 1.12.4
Method of Installation: [AUR](https://aur.archlinux.org/packages/tldr%2B%2B/), [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=tldr%2B%2B)

**Comment by iboyperson** [comment]
Upon further investigation this seems to be caused by my terminal emulator ([Konsole](https://konsole.kde.org/)) as when running `tldr` in a different emulator ([Tilix](https://gnunn1.github.io/tilix-web/)) it works as expected

**Comment by isacikgoz** [comment]
Thanks for the details @iboyperson. I also guessed that it would be a feature of the terminal emulator. So, we can close this issue for now.
