### ISSUE TITLE
go get fails

### ISSUE THREAD

**Issue by haarts** [isacikgoz/tldr#16]
Install fails:
$ go get -u github.com/isacikgoz/tldr
# cd /home/<snip>/prj/go/src/gopkg.in/src-d/go-git.v4; git pull --ff-only
Your configuration specifies to merge with the ref 'refs/heads/v4'
from the remote, but no such ref was fetched.
package gopkg.in/src-d/go-git.v4: exit status 1

Go version: go version go1.10.4 linux/amd64
OS: Pop_OS 19.04 (basically Ubuntu 19.04)
GOPATH: /home/<snip>/prj/go

**Comment by isacikgoz** [comment]
Hi @haarts thanks for the feedback. I added go modules to prevent this issues. Sorry about the inconvenience.
