### ISSUE TITLE
Go get fails with "no Go files in ..."

### ISSUE THREAD

**Issue by MatthewScholefield** [isacikgoz/tldr#20]
Not sure if I'm missing something, but I'm getting the following output when I try to install with `go get`:

```
$ go get -u github.com/isacikgoz/tldr
package github.com/isacikgoz/tldr: no Go files in /home/user/go/src/github.com/isacikgoz/tldr
```

I'm not familiar with how go packages are formatted, but it looks like it cloned the repo properly to `/home/user/go/src/github.com/isacikgoz/tldr`.

**Comment by isacikgoz** [comment]
Hey @MatthewScholefield , thanks for the feedback. It is my bad that I forgot to update the `README` file after I updated the project structure. Sorry about that.

You need to use:
```
go get github.com/isacikgoz/tldr/cmd/tldr
```

instead of 
```
go get github.com/isacikgoz/tldr
```

**Comment by MatthewScholefield** [comment]
Thanks!

**Comment by cevabveremedi** [comment]
Seems like you also forgot to update that command on your website: https://isacikgoz.me/tldr/installation/ 

Btw tldr++ is literally a lifesaver for Linux beginners like me, thanks for the good work!
