### ISSUE TITLE
go get fails due to go-git.v4

### ISSUE THREAD

**Issue by kamphaus** [isacikgoz/tldr#24]
When I tried to install using `go get github.com/isacikgoz/tldr/cmd/tldr` it failed with the error message
```
# gopkg.in/src-d/go-git.v4/plumbing/transport/ssh
/home/ckamphaus/go/src/gopkg.in/src-d/go-git.v4/plumbing/transport/ssh/common.go:147:15: undefined: proxy.Dial
```
I'm using
go version go1.13.6 linux/amd64
GOPATH="/home/ckamphaus/go"
OS is Linux Mint 19.3
Current latest commit on master is 3918253df491996b5618f2eb3de015170d63c21a.

**Comment by isacikgoz** [comment]
Updated the dependency to `github.com/go-git/go-git/v5` so it shouldn't be a problem anymore. Thanks for raising the issue. If you have any other questions feel free to open a new ticket.
