### ISSUE TITLE
Data race in package prompt

### ISSUE THREAD

**Issue by dolmen** [isacikgoz/tldr#25]
When building with `-race` (`cd cmd/tldr; go build -race; ./tldr ps`) I can easily get a data race report. 

```
==================
WARNING: DATA RACE
Read at 0x00c0001280b0 by goroutine 8:
  github.com/isacikgoz/gitin/prompt.(*Prompt).spawnEvents()
      $GOPATH/pkg/mod/github.com/isacikgoz/gitin@v0.2.3/prompt/prompt.go:180 +0xef

Previous write at 0x00c0001280b0 by main goroutine:
  github.com/isacikgoz/gitin/prompt.(*Prompt).mainloop()
      $GOPATH/pkg/mod/github.com/isacikgoz/gitin@v0.2.3/prompt/prompt.go:227 +0x364
  github.com/isacikgoz/gitin/prompt.(*Prompt).Run()
      $GOPATH/pkg/mod/github.com/isacikgoz/gitin@v0.2.3/prompt/prompt.go:145 +0x1cc
  main.run()
```

I don't know if this is related to #23, but at least this happens in the same package.

go version
```
go version go1.13.6 darwin/amd64
```
Commit: 3918253df491996b5618f2eb3de015170d63c21a

**Comment by dolmen** [comment]
In [prompt.go](https://github.com/isacikgoz/gitin/blob/master/prompt/prompt.go#L180) `p.hold` should be protected by a lock.

**Comment by isacikgoz** [comment]
I've just fixed it and it's merged to master. Please let me know if you still the issue. Also, feel free to open a new issue.
