### ISSUE TITLE
Wrong Condition and append in `ConfirmCommand` function

### ISSUE THREAD

**Issue by leninhasda** [isacikgoz/tldr#28]
In `cli/confirm.go` file from line `24:27` doesn't make sense!
```go
if s.Text() == "Y!" || s.Text() == "y!" {
	args = []string{"sudo"}
	args = append(strings.Fields(command))
}
```
Reason is, this block of code will never be executed. As `s.Text()` is either [`Y`,  `y`, ``], according to previous condition. 

Second is here `args = []string{"sudo"}`, `sudo` is never really prepended in args list as you are overriding args in next line!

A quick fix could be following:
```go
if s.Text() == "Y" || s.Text() == "y" || s.Text() == "" ||
	s.Text() == "Y!" || s.Text() == "y!" { // add those condition to previous one
	args := strings.Fields(command)
	if s.Text() == "Y!" || s.Text() == "y!" {
		args = append([]string{"sudo"}, args...) // add sudo as first arg
	}
...
}
```

Now when I tried above fix I am getting another issue:
```bash
? ls -a (Y/n) y!
args:  [sudo ls -a] # added print for log purpose
Password:panic: send on closed channel

goroutine 5 [running]:
github.com/isacikgoz/gitin/prompt.(*Prompt).spawnEvents(0xc0001440c0)
        /Users/lenin/go/pkg/mod/github.com/isacikgoz/gitin@v0.2.3/prompt/prompt.go:186 +0x119
created by github.com/isacikgoz/gitin/prompt.(*Prompt).Run
        /Users/lenin/go/pkg/mod/github.com/isacikgoz/gitin@v0.2.3/prompt/prompt.go:141 +0xd2
```

Is this a known issue to you?

**Comment by isacikgoz** [comment]
Woah, I totally missed this! Thanks a lot with raising the issue. I've just fixed it and it's pushed to master. Please let me know if you still the issue. Also, feel free to open a new issue.
