### ISSUE TITLE
WSL?

### ISSUE THREAD

**Issue by SturmB** [isacikgoz/tldr#29]
I'm using WSL on Windows 10 (hopefully soon to be using WSL2). The PC's processor is an Intel i7-7820HQ @ 2.90GHz. The flavor of Linux I'm currently running in WSL is Pengwin. I'm pretty sure it's Debian-based since it uses `apt`.

It doesn't seem like any of the release versions work for one reason or another. Which one should I get and how should it be installed?

**Comment by isacikgoz** [comment]
I never used WSL, but it would be as easy to install the tool with `go get github.com/isacikgoz/tldr/cmd/tldr` if you have a Go compiler `v1.13+`.
