### ISSUE TITLE
Go get error "not enough arguments in call to d.prompt.Run"

### ISSUE THREAD

**Issue by nguyentritai2906** [isacikgoz/tldr#30]
I have no experience with `go get` and I can't find any similar solution on the web so please excuse my ignorance. Here's the error output:

```
~ 🞂🞂 go get github.com/isacikgoz/tldr/cmd/tldr

# github.com/isacikgoz/tldr/cli
go/src/github.com/isacikgoz/tldr/cli/default.go:59:21: not enough arguments in call to d.prompt.Run
        have ()
        want (context.Context)
```

**Comment by thepenguinthatwants** [comment]
Quite annoiying problem as I've tried to figure this out whole day without any solution.

**Comment by ealeksejev** [comment]
`$ GO111MODULE=on go get -u github.com/isacikgoz/tldr`
